# Generated by Django 4.2.7 on 2023-11-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bubi_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StarWarsCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(blank=True, max_length=50, null=True)),
                ("affiliation", models.CharField(blank=True, max_length=50, null=True)),
                ("homeworld", models.CharField(blank=True, max_length=50, null=True)),
                ("jedi", models.BooleanField(default=False)),
                ("sith", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(name="Product",),
    ]
